version: "3"

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: "no"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: backend/
      dockerfile: build/package/Dockerfile
    container_name: backend
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes: 
      - ./configs/config.dev.yml:/config.yml
    environment:
      SPEAQ_CONFIG: "/config.yml"
      SPEAQ_DATABASE_HOST: "postgres"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  
  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres