version: "3"

services:
  backend:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: backend
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes: 
      - ../configs/config.dev.yml:/config.yml
    environment:
      SPEAQ_CONFIG: "/config.yml"
      SPEAQ_DATABASE_HOST: "postgres"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  
  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres